
[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/rko/alldl"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/rko/alldl"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/download/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/download/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
  
