services:
  - type: web
    name: ownrkoapi
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install --upgrade pip
      pip3 install -r requirements.txt
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
