services:
  - type: web
    name: snaptube-video-downloader
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: snaptube-video-downloader
          property: port
    healthCheckPath: /health
